### ISSUE TITLE
C-LINE (treehug): never finished (6.5 hrs)

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#14]
C-LINE Atlanta, GA, "non-cancer risk" calculation for benzene. Has been running for 6.5 hours and the little wheel is still spinning with no results showing.
![c-line_hq_noresults_12112014](https://cloud.githubusercontent.com/assets/10145737/5404157/e2a956c2-8161-11e4-81f3-a0dcb09138ef.PNG)

**Comment by michellegrace** [comment]
I understand that this is a server time-out issue with a 10-min limit on response time. If this is truly the case, there should be a warning to the user that the computation has timed out..... you could even make the suggestion to the user that "reducing the user view/modeling domain will reduce computational time".

**Comment by nathan-rice** [comment]
The timeout has been increased to 1000 seconds, which should be sufficient.
