### ISSUE TITLE
blank space at top of menus

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#17]
In the analysis window a blank space is displayed at the top of each pulldown menu. Here is a screen shot when i looked at the meteorology menu:
![screen shot 2014-12-12 at 8 33 40 am](https://cloud.githubusercontent.com/assets/10077162/5412367/002e70c4-81da-11e4-811d-7cb238737d8a.png)

Then when I click on the blank space in the pulldown menu and the blank space disappears, here is a screen shot:
![screen shot 2014-12-12 at 8 34 00 am](https://cloud.githubusercontent.com/assets/10077162/5412378/236ac11e-81da-11e4-9ea8-db0b7f85d989.png)

I checked and this happens for all menus in this window (meteorological, season, day, hour, pollutant).

Please delete the initial blank space in these menus.

C-LINE treehug version tested ~8:30am 12/12/14.

**Comment by michellegrace** [comment]
This issues seems to be fixed in the perform analysis window, but is still an issue in the compare scenario window. My hypothesis is that the blank space occurs when you have not defined a default. See examples below....
![screen shot 2015-01-15 at 12 26 53 pm](https://cloud.githubusercontent.com/assets/10077162/5762675/d21543a0-9cb1-11e4-971e-fc31491e2bb9.png)
![screen shot 2015-01-15 at 12 26 37 pm](https://cloud.githubusercontent.com/assets/10077162/5762679/d8b9ea26-9cb1-11e4-97ee-0a830d7f8086.png)

I actually think this is appropriate the way it is, if the hypothesis is correct?

If so, on C-PORT we do not want it to default to any particular city, so this is the desired behavior. 

Also if so, there should not be a default scenario in the comparison window, thus the blank space at the top of the menu.

Nathan, if you confirm my hypothesis I think this issue can be closed. However, let's try to keep this in mind as we move forward and keep this consistent.

**Comment by michellegrace** [comment]
Now I found where we are currently not consistent with the hypothesis stated above... In the compare scenarios window we have a "default" pollutant "NOx" for the hourly and annual, but when you select Cancer or non-cancer risk it is blank, see...

![screen shot 2015-01-15 at 12 37 17 pm](https://cloud.githubusercontent.com/assets/10077162/5762858/7a2ac578-9cb3-11e4-963a-d89c378b6e74.png)

Nathan, can you make the first entry is the "default" pollutant, then a pollutant would be shown with each selection? This would also need to be changed in the perform analysis window, where a pollutant is always displayed, so there is always a default.

**Comment by michellegrace** [comment]
The blank space at the top of the risk calculations cause the calculation to "hang" (see comment for issue #64), as seen here: 
![screen shot 2015-01-29 at 1 55 22 pm](https://cloud.githubusercontent.com/assets/10077162/5964055/2194d914-a7bf-11e4-99f6-c21b71d9e3bd.png)
![screen shot 2015-01-29 at 1 50 54 pm](https://cloud.githubusercontent.com/assets/10077162/5964057/2351c492-a7bf-11e4-93cf-fa3d3cc50bbd.png)

There should be a default for this menu and not a blank space, this default could be "Benz", the first pollutant in the drop down menu. If this is not feasible a warning to the user that blocks them from submitting the calculation (like in compare window for geographic extent) saying "Please select a pollutant" would also be sufficient and prevent this from hanging.

I have increased this issue to "critical", because it is something that would cause the user to think the tool is broken or not working correctly.

**Comment by nathan-rice** [comment]
Selected pollutant is changed to benz when cancer or non cancer risk are selected.
