### ISSUE TITLE
Compare scenarios tab needs work

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#25]
Here is a screenshot:
![screen shot 2014-12-16 at 1 32 23 pm](https://cloud.githubusercontent.com/assets/10077162/5459453/180dca58-8529-11e4-8653-193f3e9e4877.png)

I would like multiple changes to made to this tab:
(1) You should clearly state that you are computing hourly or annual average (for risk).
(2) Please give the user a sense of runtime, put "(... min runtime)" next to each option.
(3) Only certain pollutants have cancer/non-cancer risk. These are Benz, FORM, ALD2, ACRO (non-cancer only), and 1,3-BUTA. All other pollutants should only have the option of hourly or annual average concentration computations.

Tested C-LINE on treehug ~1:30pm 12/16/14.

**Comment by michellegrace** [comment]
This has still not been addressed.....
Please change the question to "What would you like to compare?" then the radio buttons should be 
Hourly concentrations (~1 min runtime) 
Annual average concentrations (>5 min runtime)
Cancer risk from annual average (>5 min runtime)
Non-cancer risk from annual average (>5 min runtime)

This needs to be done BEFORE the release!

**Comment by nathan-rice** [comment]
Done
