### ISSUE TITLE
Title on the scenario tab

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#26]
This seems to be missing. The title should be "Load a previous scenario", or something of the like...

Dont remember exactly what it was before, but all tabs should have titles. Here is a current screen shot...
![screen shot 2014-12-16 at 3 30 24 pm](https://cloud.githubusercontent.com/assets/10077162/5461369/bf021c38-8538-11e4-93f7-0cbb11edbe2c.png)

Tested C-LINE on treehug ~3:30pm 12/16/14.

Thanks.

**Comment by nathan-rice** [comment]
Fixed
