### ISSUE TITLE
Lock Map Data help menu off screen

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#27]
It looks like the "lock map data" button was moved to the bottom of the user view, which is great. Please make the menu pop up to the right, but above the help button (not centered on the button). A screenshot is provided.
![screen shot 2014-12-17 at 8 58 47 am](https://cloud.githubusercontent.com/assets/10077162/5472136/4d22ec9e-85cb-11e4-9e31-ed050ae6a86c.png)

tested C-LINe on treehug ~9:00am 12/17/14.

**Comment by nathan-rice** [comment]
Done
