### ISSUE TITLE
Compare scenarios should have 4 options

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#31]
The current window looks like this:
![screen shot 2015-01-07 at 12 25 26 pm](https://cloud.githubusercontent.com/assets/10077162/5649982/8866d146-9668-11e4-9c57-0f5639a1e657.png)

There should be 4 types of comparison. 
(1) Hourly concentrations (these uses stable, slightly stable , neutral, slightly convective, and convective meteorology)
(2) Annual average concentrations (these don’t use the above)
(3) Cancer risk from annual averages
(4) Non-cancer risk form annual averages

I envision these looking something like this (obviously in a larger font size to match, but you get the idea):
![screen shot 2015-01-07 at 12 36 28 pm](https://cloud.githubusercontent.com/assets/10077162/5650167/f32ec4e2-9669-11e4-9649-c45ba24c2c12.png)

Each of these are outputs of the C-LINE code.....
(1) The hourly concentrations are output by the code when CLINE_D+E.ifort.x is called:
![screen shot 2015-01-07 at 12 49 33 pm](https://cloud.githubusercontent.com/assets/10077162/5650355/a7d903ca-966b-11e4-9914-750b1fa77064.png)

(2,3&4) Are based on the annual average and they are output when AA_CLINE_D+E.ifort.x is called:
![screen shot 2015-01-07 at 12 53 25 pm](https://cloud.githubusercontent.com/assets/10077162/5650410/30fc1a98-966c-11e4-9d1b-edbf19088431.png)

**Comment by michellegrace** [comment]
This is looking better on treehug (~9:15am 1/8/15), except there are a few small bugs...

(1) The annual average concentration option should be available for ALL pollutants. Currently this is only available for a selected number, see screen shot below:
![screen shot 2015-01-08 at 9 20 53 am](https://cloud.githubusercontent.com/assets/10077162/5663661/cc30ed44-9717-11e4-92c8-4cb96eda8097.png)

This should have all pollutants like the hourly concentration option:
![screen shot 2015-01-08 at 9 22 13 am](https://cloud.githubusercontent.com/assets/10077162/5663672/e7a8e964-9717-11e4-8ff2-2e7345a7b25b.png)

(2) The Non-cancer risk option does not have a menu to select pollutants & cancer risk does not have the correct pollutants:
![screen shot 2015-01-08 at 9 23 05 am](https://cloud.githubusercontent.com/assets/10077162/5663688/089c6b96-9718-11e4-92e9-45f170f08ca9.png)

Just as a reminder the cancer and non-cancer risk should have the following pollutant options...
Cancer: Benzene, Form, ALD2, 1,3-buta
Non-Cancer: Benzene, Form, ALD2, ACRO, 1,3-buta

**Comment by joellenb** [comment]
This is what the options are looking like now (afternoon of 1/8/2015). I believe that the "concentrations or health risks" question and options were displayed after I selected the annual temporal option. I did not check the chemical list for each option.

![c-line_benzene_atlanta_4options_01082015](https://cloud.githubusercontent.com/assets/10145737/5670666/f02ec2e2-974f-11e4-9860-3d2f0fba6354.PNG)

**Comment by joellenb** [comment]
On the Compare scenarios this afternoon the Hourly concentrations lists 11 chemicals, Annual average concentrations lists 4 chemicals (should be all chemicals), Cancer risk lists 5 chemicals, and Noncancer risk does not have a pollutant drop-down box at all.

Also, what sorting rules are currently implemented for the chemicals in the list? They appear to be random but repeatable. I suggest alphabetical order increasing from A to Z would be preferable.
![c-line_nopollutantbox_noncancer_01082015](https://cloud.githubusercontent.com/assets/10145737/5671562/dc5ef5dc-9756-11e4-974c-d1cb9b032cfa.PNG)
![c-line_cancerchem_01082015](https://cloud.githubusercontent.com/assets/10145737/5671611/51f1e3d6-9757-11e4-85d2-28117640e81d.png)
![c-line_annualconc_01082015](https://cloud.githubusercontent.com/assets/10145737/5671704/1b2acf06-9758-11e4-8e9c-bc12e2abbd70.png)
![c-line_hrconc_01082015](https://cloud.githubusercontent.com/assets/10145737/5671753/684eda48-9758-11e4-962d-9e7e9b402ebf.png)

**Comment by michellegrace** [comment]
This appears to be fixed int he latest version on treehug 1/13/15 1:45pm.
