### ISSUE TITLE
Local saved scenarios listed incorrectly

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#33]
The Atlanta scenario shown in this graphic was for an annual scenario. But C-LINE is showing it as an hourly scenario (Neutral, winter, weekday, AM Peak). I do have 3 Firefox sessions open (this GitHub session, the Atlanta scenario, and a Knoxville scenario) so I don't have to wait while the Atlanta scenario grinds. The only difference between the 

![c-line_savedscenarios_01082015](https://cloud.githubusercontent.com/assets/10145737/5670789/17c88f08-9751-11e4-8f43-c051b72ab5fe.PNG)

**Comment by joellenb** [comment]
"Load a previous scenario" window on the Atlanta session and the Knoxville session is that the Atlanta line on the Atlanta session is printed in red. The screen capture shown in these comments was taken from the Knoxville session.

**Comment by michellegrace** [comment]
I find a similar problem... when I save a scenario for Charelston (summer & stable):
![screen shot 2015-01-12 at 1 25 34 pm](https://cloud.githubusercontent.com/assets/10077162/5708422/c72af318-9a5e-11e4-8f23-4d59fd65205b.png)

In the load a scenario window this has an incorrect met condition and season:
![screen shot 2015-01-12 at 1 25 50 pm](https://cloud.githubusercontent.com/assets/10077162/5708439/e1f588d4-9a5e-11e4-87e8-f877e499548d.png)

The incorrect saving can be related to the compare scenarios leading to no difference (see #24).

This needs to be fixed before the release.

**Comment by michellegrace** [comment]
Also note, when I go back and refresh the site and load the stable & summer scenario, it loads as stable & winter.

**Comment by nathan-rice** [comment]
Fixed
