### ISSUE TITLE
"Clobbering" issue still not resolved or user options not updating.

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#34]
I opened 2 C-LINE instances in separate windows.... 
![screen shot 2015-01-12 at 1 36 13 pm](https://cloud.githubusercontent.com/assets/10077162/5708595/7eed940a-9a60-11e4-8bc4-943e6d92ea94.png)

The one to the left is stable & summer; the one to the right is convective & winter. I hit submit within 5 seconds of each other (stable & summer then convective & winter) and the results are shown here...
![screen shot 2015-01-12 at 1 37 13 pm](https://cloud.githubusercontent.com/assets/10077162/5708625/b9287cde-9a60-11e4-965d-21ef0e5f07d6.png)

and here...
![screen shot 2015-01-12 at 1 41 52 pm](https://cloud.githubusercontent.com/assets/10077162/5708636/d2af96ba-9a60-11e4-948f-115cc666d1c6.png)

These appear to be identical (even the scales)... in fact they popped back to my screen within 5 second of each other.  

Then I re-ran each window separately and the results are still identical.. this is incorrect. So I went to my offline version and ran with the same 2 option combinations. See..

/nas01/depts/ie/cempd/EPA-RARE/MGScode/CLINE_DispEmis_11-19-14/Charleston_Stable_Summer

![charl_stable_summer_intoutputs_log](https://cloud.githubusercontent.com/assets/10077162/5708896/0097c4ba-9a63-11e4-9cd2-4ebd04475fea.png)

 /nas01/depts/ie/cempd/EPA-RARE/MGScode/CLINE_DispEmis_11-19-14/Charleston_Convective_Winter

![charl_convective_winter_intoutputs_log](https://cloud.githubusercontent.com/assets/10077162/5708897/07130da4-9a63-11e4-8846-7c0741aba15b.png)

Although these both show the road network, the wind direction in the summer appears to be blowing from south to north, in the winter from Northwest to Southeast. In addition, the scale from the winter has a shift of an order of magnitude lower than in the summer. These features are not present in the web-based version.

It is possible that this is related to Jo Ellen's issue that the scenarios are not displaying the correct user selections when you save a scenario(#33).

**Comment by nathan-rice** [comment]
The two overlays are clearly not perfectly identical, and it is expected that if you started them within 5 seconds they would finish within 5 seconds.  That being said, there may be an issue with settings not being propagated properly, I will look into it.

**Comment by nathan-rice** [comment]
This is caused by the same bug as issue 33.  Fixed.
