### ISSUE TITLE
Unable to select roadlinks

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#35]
I am unable to select roadlinks by clicking on them.

Tested on treehug 1/13/14 1:45pm.

**Comment by joellenb** [comment]
Problem confirmed on treehug 1/14/2014 5:12 pm. Tried it both from work computer and remotely from home computer. On both was able to use the mouse to "grab" a line segment as indicated by the hand changing to a pointing finger. But the segment did not show in the roads panel and the road segment was not highlighted (change of color) on the map.

**Comment by nathan-rice** [comment]
Fixed
