### ISSUE TITLE
The default for gas/diesel car/truck multipliers do not update

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#36]
On C-LINE view and modify roads when I click on a multiplier it is blank....
![screen shot 2015-01-13 at 1 46 47 pm](https://cloud.githubusercontent.com/assets/10077162/5726615/cdada97a-9b2a-11e4-8b4c-be6650f49d28.png)

Then I clicked the up arrow and it goes to 0.1, 
![screen shot 2015-01-13 at 1 48 24 pm](https://cloud.githubusercontent.com/assets/10077162/5726650/0d5bc340-9b2b-11e4-946d-c4512f8a5a88.png)
The default value started at 1, if I hit the up arrow it should go to 1.1.....

Then I selected something else, and the change was not updated....
![screen shot 2015-01-13 at 1 50 53 pm](https://cloud.githubusercontent.com/assets/10077162/5726675/354abbfe-9b2b-11e4-9aa6-5be07f436197.png)

C-LINE on treehug 1/13/15 1:45pm

**Comment by michellegrace** [comment]
This is a two-fold problem....
The "default" value should be the value that is present int he database. So if the user clicks the up arrow this should increase by one increment (in this case 0.1) giving the new multiplier as 1.1, vice versa for the down arrow. This is how the AADT and speed values work, it should be the same for the multipliers.  

The second problem with the editable boxes for the multipliers is that they are not updating when the multiplier is changed.

**Comment by nathan-rice** [comment]
Fixed
