### ISSUE TITLE
Individual hours work but compare scenarios does not

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#37]
I ran the case for Charleston, SC in winter & convective vs summer & stable conditions, all other parameters were the same.....

(1) Winter & convective
![screen shot 2015-01-13 at 2 15 25 pm](https://cloud.githubusercontent.com/assets/10077162/5727116/a4b03fc0-9b2e-11e4-8616-d816ce16c447.png)

(2) Summer & stable
![screen shot 2015-01-13 at 2 16 25 pm](https://cloud.githubusercontent.com/assets/10077162/5727132/c76073e6-9b2e-11e4-9564-06ef5f6d4066.png)

(3) Compare (just sits there and spins... over 5 minutes now
![screen shot 2015-01-13 at 2 18 31 pm](https://cloud.githubusercontent.com/assets/10077162/5727182/15fc0664-9b2f-11e4-8283-e3ed62ee0dc4.png)
)

Tested on treehug C-LINe 1/13/15 ~ 2:15pm.

**Comment by michellegrace** [comment]
This could be a similar issue to #24...

**Comment by nathan-rice** [comment]
Fixed......
