### ISSUE TITLE
Annual averages not working at all

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#41]
Sarav and I tried to run a C-LINE annual average computation in the perform analysis window on his computer for Atlanta, GA. The spinning wheel just keeps spinning and it never finishes, so he terminated the submission after about an hour.

I tested this on my machine in my office for Raleigh, NC and the same story, I terminated this after 20 minutes. 

In a previous closed issue (#14) the time-out threshold was increased to 1000 seconds, this seems to still be insufficient, or there is an error when setting up the annual average computations and the submission gets "stuck". 

Note: this is a separate, but related issue to #40.

Tested this on treehug between 1pm and 2:45pm on 1/14/15.

**Comment by nathan-rice** [comment]
Fixed
