### ISSUE TITLE
Load a scenario window does not change pages

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#42]
When I go to the load a scenario window I see this...
![screen shot 2015-01-15 at 12 01 13 pm](https://cloud.githubusercontent.com/assets/10077162/5762192/7922acb8-9cae-11e4-87c9-5f840be3d26e.png)

Here it appears that there is a second page, but when I click on the second page the scenario list does not change, see it here...
![screen shot 2015-01-15 at 12 01 25 pm](https://cloud.githubusercontent.com/assets/10077162/5762203/8f025f7e-9cae-11e4-89d9-70115061c7aa.png)

This window structure is similar to the view and modify roads window, but in this window as i move through the pages the roadways change. See the next 2 images...
![screen shot 2015-01-15 at 12 05 13 pm](https://cloud.githubusercontent.com/assets/10077162/5762232/c82df6a0-9cae-11e4-8938-d083b13e66c3.png)
![screen shot 2015-01-15 at 12 04 55 pm](https://cloud.githubusercontent.com/assets/10077162/5762235/caac11dc-9cae-11e4-85de-a1b5f9daef05.png)

I tested this on treehug ~12noon 1/15/15. I wanted to be clear, this is hopefully a small item that can be fixed before the release.

**Comment by nathan-rice** [comment]
Fixed
