### ISSUE TITLE
2 things missing from "download files" package

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#43]
1. The headings are still wrong in the Concentrations.csv file.
![wronghdr_concentrationcsv_01162015](https://cloud.githubusercontent.com/assets/10145737/5779636/72658232-9d72-11e4-8348-b7b2eceb5737.PNG)

2. There is no way for the user to know what scenario is represented by the downloaded file. It is named results.tar.gz and no identifying information is included within it. We need something that is both easy to implement and obvious to the user. If the data downloaded were for a saved scenario, perhaps include a README.txt file containing the name of the scenario. If possible also include the information shown on the Perform Analysis screen. That would work whether or not the scenario were a "saved scenario".

**Comment by nathan-rice** [comment]
Don't know what to tell you, the concentrations.csv file is just the file written out by CLINE

**Comment by michellegrace** [comment]
I verified that this is an issue only with NOx header in the output file for hourly and annual average.... this is a mistake in my code. I fixed it, so now...

Please use the executables in the directory:
 /nas01/depts/ie/cempd/EPA-RARE/MGScode/CLINE_DispEmis_1-26-15

I used the offline version of the Charleston input files and these can be found in the same directory under the "Charleston" folder.

Nathan please close this issue when you update the executables and verify that this fixed the issue.

**Comment by michellegrace** [comment]
I think #2 is worth addressing in a future release. I will add this as a separate issue. This needs some discussion, maybe we can get an auto-generated file with the a dialogue of run scripts and/or options.

**Comment by nathan-rice** [comment]
Updated
