### ISSUE TITLE
2 text strings on Perform Analysis window

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#44]
I expect that these two things would be easy to fix. 

1. This is the only panel where more than one word is capitalized in the title: Perform Analysis. Others are "Select your location", "Load a previous scenario", "View and modify roads", and "Compare scenarios". Please make them consistent.
2. "Would you like to compute?" should be changed to "What would you like to compute?".
![performanalysis_01162015](https://cloud.githubusercontent.com/assets/10145737/5779813/ef797e26-9d73-11e4-88ac-73b025dc2a78.PNG)

**Comment by nathan-rice** [comment]
Changed
