### ISSUE TITLE
Order of saved scenarios in load a scenario window

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#45]
I saved a scenario on the perform analysis window, like this....
![screen shot 2015-01-16 at 11 58 12 am](https://cloud.githubusercontent.com/assets/10077162/5780256/210ee748-9d77-11e4-80e3-2c5f931717b8.png)

When I went to the scenario window to see if it was saved, I thought it was not saved because I was this..
![screen shot 2015-01-16 at 11 58 20 am](https://cloud.githubusercontent.com/assets/10077162/5780266/35e984a2-9d77-11e4-9f13-24cdf7e4622e.png)

However, this scenario was saved, it was on the second page...
![screen shot 2015-01-16 at 11 57 39 am](https://cloud.githubusercontent.com/assets/10077162/5780276/47df4264-9d77-11e4-941c-19fbeb8f4e67.png)

This can be confusing for the user, because they do not see their saved scenario immediately. Can you make the scenarios in order that they are saved(with most recent being the first entry on the first page)?

Thanks.

tested on treehug ~12noon 1/16/15.

**Comment by nathan-rice** [comment]
Newly saved scenarios will now be inserted at the start of the scenario list
