### ISSUE TITLE
AADT multiplier should not require integer

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#46]
In C-LINE, View and modify roads, when multiple roads are selected the AADT multiplier up/down arrow widget is displayed. The up/down should increment/decrement by 0.1 (not by integers).
If I manually type in a decimal value (e.g., 1.2) the widget is outlined in red and hovering the mouse displays the message:
Please select a valid value. The two nearest valid values are 1 and 2.

Please make the widget increment/decrement by 0.1 and remove the requirement for integer input.

**Comment by nathan-rice** [comment]
I don't require that this value is an integer anywhere.  Changed the step size to 0.1 though...
