### ISSUE TITLE
Incorrect differences mapped and downloaded

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#47]
Compare scenarios: There are actually a couple problems here, but I believe that they are related.

1-hr base case:
![stblwinternox_01162015](https://cloud.githubusercontent.com/assets/10145737/5780876/04d5dbe0-9d7c-11e4-82fa-e10f1a45609f.PNG)

1-hr new case:
![convsummnox_01162015](https://cloud.githubusercontent.com/assets/10145737/5780888/14ae8c2e-9d7c-11e4-973c-6d956b270b0d.PNG)

Relative difference (New - Base): Range Max New = 100, Range Max Base = 1000, expect negative values in map and "concentrations" file but values in 4th column of concentrations.csv ranged 0.0 - 785.34. 
NOTE: Some values shown on map are negative, so mapped values do not match downloaded values.
![athens_relcomp_01162015](https://cloud.githubusercontent.com/assets/10145737/5780936/6d9b8e7c-9d7c-11e4-8b46-67a365f802a6.PNG)

Relative % difference: (New - Base) / Base * 100%: expect some negative values in map and "concentrations" file but values in 4th column of concentrations.csv had same range as "relative difference" above and percentage values in map are all positive.
![athens_relpercntcomp_01162015](https://cloud.githubusercontent.com/assets/10145737/5781007/08cc71cc-9d7d-11e4-8c63-f4113c055028.PNG)

**Comment by nathan-rice** [comment]
The concentrations file produced is just the output from the fortran executable, as I've stated previously.

The visualization is correct, I've verified that the input data and computations being performed are all as they should be.

**Comment by michellegrace** [comment]
Ok I went through every step of an example application, here are my steps and results....

(1) I determined a good road link to show windows and selected link. I determined the stretch of US1 south of Raleigh, into Cary provided a good test case.
![screen shot 2015-01-26 at 9 20 06 am](https://cloud.githubusercontent.com/assets/10077162/5901135/f806fed4-a53d-11e4-985a-f9091f4a560b.png)

(2)  I made & saved "Raleigh_Base", where I ran NOx hourly with all the default met options.
![screen shot 2015-01-26 at 9 24 04 am](https://cloud.githubusercontent.com/assets/10077162/5901138/fb4a762a-a53d-11e4-8dea-7231cd778614.png)

(3) I changed the AADT of this stretch of US1 from ~91000 to 300000 (an increase of ~3x).
![screen shot 2015-01-26 at 9 20 27 am](https://cloud.githubusercontent.com/assets/10077162/5901153/18fe27f2-a53e-11e4-8883-4fa10a26755c.png)

(4) Then I re-ran hourly NOx with the default met options, and saved this scenario as "Raleigh_incUS1".
![screen shot 2015-01-26 at 9 22 53 am](https://cloud.githubusercontent.com/assets/10077162/5901157/2a3e68a6-a53e-11e4-9403-95bc9924ca37.png)

(5) I then compared the scenarios to find the relative difference. (This appears to be correct)
![screen shot 2015-01-26 at 9 25 32 am](https://cloud.githubusercontent.com/assets/10077162/5901173/4db354fe-a53e-11e4-8dc5-8108d5275a49.png)

(6) Then I compared the scenarios to find the relative % difference. (This appears INCORRECT**).
![screen shot 2015-01-26 at 9 27 10 am](https://cloud.githubusercontent.com/assets/10077162/5901181/697cb68a-a53e-11e4-9792-d055975f6268.png)

** From the help menu this is defined as Relative (%) Mode: Calculated as (New - Base)/Base X 100. 

The other difference option, Relative Mode: Calculated as (New - Base) is the numerator in the % calculation, so if the relative difference is positive, then the % should be positive. This is not the case for %. I expect the % image to be the same as the relative difference, but the color scales would be different. 

In addition (possibly for a future release, if too difficult?), for these comparison plots the color scale should be transparent at 0, then go from yellow to orange to red if positive difference and green to blue to purple for negative differences. This would use a logical color scheme so increased exposures would be "hot" and decreased exposures would be "cold".

**Comment by nathan-rice** [comment]
While it might appear to be incorrect, the difference between relative and relative (%) is literally one line of code:

    if data.get("mode") == "Relative":
        concentrations[:, 2] -= concentrations_2[:, 2]
    else:
        concentrations[:, 2] = (concentrations_2[:, 2] - concentrations[:, 2]) / concentrations[:, 2] * 100

Which as you can see is the calculation you specified.

**Comment by michellegrace** [comment]
Nathan, thanks for including this code in your response. If I am interpreting this correctly, i think there is a mistake here....

I assume from your code,
(1) concentrations = new
(2) concentrations_2 = base

If these are correct, 
Relative=new-base, which is correct.

However, 
Relative % = (base-new)/base *100 

If these assumptions are correct, can you please modify the Relative % to be:

concentrations[:, 2] = (concentrations[:, 2] - concentrations_2[:, 2]) / concentrations_2[:, 2] * 100

Thanks.

**Comment by nathan-rice** [comment]
Actually, it's the opposite, concentrations_2 = new, concentrations = old.

**Comment by michellegrace** [comment]
Well either way, it looks like the relative % is flipped from the relative difference. Please check this.
Thanks.

**Comment by nathan-rice** [comment]
Fixed
