### ISSUE TITLE
Wrong analysis performed

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#48]
I suspect that something is not being reset properly as the user clicks among the 4 selections and the pollutant. I ended up on the Annual average concentration for NOx, but the legend for the results show ALD2 cancer risk.
![wronganalysisperformed_01162015](https://cloud.githubusercontent.com/assets/10145737/5781616/48cc2948-9d82-11e4-8724-d291dbd12b3c.PNG)

**Comment by joellenb** [comment]
Here is another example. This one selected was for noncancer ALD2, but the legend shows concentration for ALD2.

![wronganalysisperformed2_01162015](https://cloud.githubusercontent.com/assets/10145737/5784225/2f69f5d2-9d98-11e4-93c0-a6ae6bb8b845.PNG)
When I select cancer for benzene, it gives me noncancer for benzene.

![wronganalysisperformed3_01162015](https://cloud.githubusercontent.com/assets/10145737/5784260/89a54448-9d98-11e4-8f88-1e0c08dceefa.PNG)
Annual average concentration for acrolein gives cancer risk for acrolein.

![wronganalysisperformed4_01162015](https://cloud.githubusercontent.com/assets/10145737/5784299/f9950838-9d98-11e4-9d56-7526d89c1919.PNG)

Here annual average concentration for NOx gives cancer risk for NOx. That is really impossible, though, because NOx is not a carcinogen!

![wronganalysisperformed5_01162015](https://cloud.githubusercontent.com/assets/10145737/5784345/6616ecce-9d99-11e4-9be4-b6eed7623c29.PNG)

**Comment by nathan-rice** [comment]
Fixed
