### ISSUE TITLE
Incorrect units for pollutants

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#49]
The concentrations for NOx and CO are given by the dispersion program in ppb. This is reflected in the output file that the user can download, but is incorrect in the label on the image.....
![screen shot 2015-01-16 at 1 08 25 pm](https://cloud.githubusercontent.com/assets/10077162/5781508/622a96b4-9d81-11e4-89fc-cdc6addd378d.png)

Also headers are not consistent with the number of columns (see #43), you should be able to output the exact file that the dispersion code outputs.

The minimum of 10^-6 micrograms/m^3 is for concentrations. These pollutants do not have the same minimum since the output is in ppb and the minimum ppb is different for all hours that are run because the conversion of concentration to ppb uses the temperature. This headache is why I initially filtered results for a minimum concentration of 10^-6, cause in the dispersion model this can be done before the conversion to ppb. 

Tested on treehug ~1:15pm 1/16/15.

**Comment by nathan-rice** [comment]
changed
