### ISSUE TITLE
Help button location in perform analysis window

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#50]
The help button for the "What would you like to compute?" (#44) question is directly below the scenario name help button. This is confusing, all other help buttons are at the end of the text or object in a line.
![screen shot 2015-01-16 at 1 28 34 pm](https://cloud.githubusercontent.com/assets/10077162/5781829/cda8cf3a-9d83-11e4-9acd-1e8cce275686.png)

Please move the location of this button to directly after the "?".  Thanks.

tested on treehug ~1:30pm 1/16/15.

**Comment by nathan-rice** [comment]
done
