### ISSUE TITLE
Compare scenarios different geographic domains does not produce error

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#51]
Have 2 different domains of Athens, GA: (1) Athens and surrounding area, (2) zoomed in on central and eastern part of Athens proper. Did "Compare scenarios" in Relative mode with small domain as "new" and larger domain as "old". Unchecked the "Lock map data" prior to submitting.

Hourly concentration went into the little circle spinning mode and did not come back.

Correct behavior is for the Compare scenarios to check that the 2 scenarios have identical domain extents. (That is why our help says to lock the data before saving 1 scenario and using that as the basis for the other scenario, keeping the geographic extent locked all the way through the save.)

If the geographic extents do not match, then the program should display an error message to the user immediately and stop calculations.

**Comment by joellenb** [comment]
NOTE: Let this scenario run for over 30 minutes and no result was ever produced. Expected a timeout message to the user but wheel just kept spinning.

**Comment by nathan-rice** [comment]
Done
