### ISSUE TITLE
View and modify roads: need to implement a minimum on speeds

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#52]
When selecting multiple roads and applying a speed change to the range, the resulting new value should have a minimum below which it cannot go. For example, I just selected several adjacent sections of highway and then applied a change to AM of -45. Most went to 10 but one segment that had a slower speed was changed to -2.

I suggest a minimum speed of 10 MPH for all 4 speed categories. I don't believe that an hourly average speed on any road segment would be less than 10 MPH.

![negativespeed_01162015](https://cloud.githubusercontent.com/assets/10145737/5783271/73191eba-9d8f-11e4-86d7-69a96795c748.PNG)

**Comment by nathan-rice** [comment]
Done
