### ISSUE TITLE
The relative differences are wrong

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#55]
I ran the same scenarios that I had in #47, now the relative difference AND % are INCORRECT. 

(1) Relative difference:
![screen shot 2015-01-26 at 12 42 19 pm](https://cloud.githubusercontent.com/assets/10077162/5904740/cbcd32fa-a558-11e4-884e-660477706892.png)

(2) Relative %:
![screen shot 2015-01-26 at 12 40 15 pm](https://cloud.githubusercontent.com/assets/10077162/5904729/bc222504-a558-11e4-8d73-4f0fed3dd288.png)

I increased the AADT, the NOX % and relative differences should both be positive.

**Comment by nathan-rice** [comment]
Fixed
