### ISSUE TITLE
AADT multiplier with multiple road links selected

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#56]
This was addressed in issue #46. This issue was closed and the multiplier was suppose to increment by 0.1, however this is not the case, the multiplier changes in increments of 1. 

Please make this multiplier in increments of 0.1, then the value displayed once the multiplier is applied should always be an integer.

Thanks.

**Comment by nathan-rice** [comment]
This is working on my end.  Try doing a full refresh - you are probably using cached assets.

**Comment by michellegrace** [comment]
I just refreshed twice and cleaned out my history and refreshed twice, the multiplier adjustment for AADT when multiple links are selected has increments of 1, not 0.1.

I am using safari on a mac.

I also clear the history and refreshed multiple times on my firefox browser and get the same behavior.

**Comment by nathan-rice** [comment]
Don't know what to tell you, treehug works properly for me in firefox and chrome.

**Comment by joellenb** [comment]
Confirmed that the increment on the AADT for multiple road segments is still an integer and is marked in a red box when I put in a decimal value. The AADT multiplier should start at 1 and then increase using an increment of 0.1, decrease using a decrement of 0.1 (or increment of -0.1), and have a lower bound of 0 (remove all traffic from the selected road segments).

**Comment by michellegrace** [comment]
These multipliers are still increasing/decreasing by an increment of 1, instead of 0.1. 

When I press the up arrow I get "1", then "2":
![screen shot 2015-01-27 at 10 03 11 am](https://cloud.githubusercontent.com/assets/10077162/5920590/b84ac9d2-a60b-11e4-90bb-47d6dc5d3eb5.png)

This should be fixed, so when I press the up arrow I get "1.1", i.e. this multiplier value will increase the AADT by 10%. 

Also, the issue with the car/truck gas/diesel multiplier should have the same behavior. This was addressed in issue #36, but is still not completely fixed. The increments are correct at 0.1, but the starting number should be 1, I am fine with a "1" appearing in these multiplier boxes, then the arrows to increase and decrease changing this by an increment of 0.1 (i.e. 10%). If you have a "1" appearing in the multiplier boxes you should have a "0" appear in the change boxes for the speeds.

**Comment by nathan-rice** [comment]
Trying a different fix for this, let me know if it works for you...

**Comment by michellegrace** [comment]
This appears to be working well in the current version (treehug ~12.30pm 1/28/15).
