### ISSUE TITLE
Font size of "What ... compute?"

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#57]
The font size of the question "What would you like to compute?" is very different on the perform analysis and compare scenarios window. 
![screen shot 2015-01-26 at 1 07 15 pm](https://cloud.githubusercontent.com/assets/10077162/5905205/78ab23f8-a55c-11e4-92ad-8809827b9258.png)
![screen shot 2015-01-26 at 1 07 07 pm](https://cloud.githubusercontent.com/assets/10077162/5905206/7ad973a0-a55c-11e4-8d02-e879fc6db4b1.png)

Please make these consistent, personally I like the thicker/bolder font on the perform analysis tab.

**Comment by nathan-rice** [comment]
Fixed
