### ISSUE TITLE
Downloaded results in comparison window

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#59]
I am confused on what the files in the downloaded results folder. What is the difference in "results.csv" and "concentrations.csv"? Shouldn't there be 2 concentration files? Then possibly a "results" or "difference" or "percent_difference" file?

There should be 2 concentration.csv files one for "base" and one for "new". Then a "difference.csv/results.csv/percent_difference.csv". if this file is "results.csv" there needs to be a note on how this was computed, i.e. difference or percent difference. 

Anyways, there needs to be some more work here to make this clear to the user.

**Comment by michellegrace** [comment]
Sorry I forgot the screenshot.
![screen shot 2015-01-26 at 2 53 10 pm](https://cloud.githubusercontent.com/assets/10077162/5907647/a0b64af0-a56e-11e4-9999-062760434998.png)

**Comment by nathan-rice** [comment]
Results is the final computed difference/etc.  Concentrations.csv is the file output by CLINE.

I can rename them if that would help clarify things.

**Comment by michellegrace** [comment]
There should be 2 output concentration.csv files, cause you run CLINE twice, once for each scenario that is being compared.

In this case I changed a source, so there should also be 2 source files. One with the "base" sources, and one with the "new" sources.

A suggestion.... You are outputting a zip file, in the top directory have "results.csv" and "receptors.csv", since these are common to both runs. Then have 2 sub-directories: "New" and "Base"... these subdirectories will each contain 4 files: (1) scenario name; (2) sources; (3) CLINE_inputs.txt; and (4) concentration.csv. If its easier to have the receptor file in the subdirectories that would also be fine.

**Comment by michellegrace** [comment]
This also needs to be clarified/revised for the single scenario case, where you are running hourly, annual or risk. In the downloaded results there is a file called "concentrations" and one called "results".
![screen shot 2015-01-27 at 11 15 23 am](https://cloud.githubusercontent.com/assets/10077162/5921994/0a010a02-a616-11e4-8f18-bb6774f0a146.png)

The results file appears to have all the 0 concentrations changed to 1*10^-6. This is needed for the interpolation, I suppose, but this is not good for the user to have. I suggest leaving the results file out of the downloaded file.

**Comment by nathan-rice** [comment]
That isn't just needed for interpolation, it is also needed for log scaling.

The results file is needed for comparison cases, but I have remove it for single scenario cases.
