### ISSUE TITLE
Units wrong on scale

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#60]
I ran the annual average for NOx in Charleston. The annual average concentration for Nox should be in ppb, this is still not fixed eventhough issue #49 was closed.
![screen shot 2015-01-27 at 10 20 48 am](https://cloud.githubusercontent.com/assets/10077162/5920944/58e68366-a60e-11e4-909c-cee47540ae62.png)

![screen shot 2015-01-27 at 10 30 35 am](https://cloud.githubusercontent.com/assets/10077162/5921117/8cf0e484-a60f-11e4-9d25-e28390cb2f12.png)

These units must be consistent with the header of the C-LINE outputs. I am including a list of all units to be clear and complete:
Hourly or Annual average: NO & CO in "ppb", all others in "micrograms/m^3".
Cancer or Non-Cancer risk: all available pollutants in "incidence per million".

tested on treehug 1/27/15 ~10:15am.

**Comment by nathan-rice** [comment]
Fixed
