### ISSUE TITLE
The relative  still does not look correct.

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#62]
I ran the same scenario as in issues #47, #55, and #58, where I increased the AADT on the stretch of US1 to the south west of Raleigh. I get a relative difference plot that looks correct. 
![screen shot 2015-01-27 at 2 15 12 pm](https://cloud.githubusercontent.com/assets/10077162/5925051/efbb14f8-a62e-11e4-8714-673ad27b9d1d.png)

Then I run the % difference, this is incorrect! The majority of the map has 0.0 relative difference, how can that be a 100% difference? (It should be a relative % difference of zero, since % is relative difference*100/base).
![screen shot 2015-01-27 at 2 12 23 pm](https://cloud.githubusercontent.com/assets/10077162/5925060/10c40290-a62f-11e4-8a24-198e63857701.png)

**Comment by nathan-rice** [comment]
I just made a small tweak on treehug.... Try this again

**Comment by michellegrace** [comment]
ok after refreshing the C-LINE page I tried this again. In my first post, I said I increased the AADT, but from the relative difference and my scenario names it looks like I actually decreased the AADT, sorry, but the same concern remains.

I used the same scenario and the decreased AADT for this stretch of US to the southwest of Raleigh. 

The relative difference looks correct and the same as above.

When I compute the % difference I get a plot that looks incorrect:
![screen shot 2015-01-28 at 9 36 24 am](https://cloud.githubusercontent.com/assets/10077162/5939381/2e7518cc-a6d1-11e4-9d4f-31c5b0eca5bf.png)

If the color scale is still the -100% to 100% where -100% is transparent I would agree that the majority of this plot should be green, inducing 0% difference. However, there should be a gradient of color to the southeast of the segment that was changed. BTW, the color on the scale/legend is missing. 

I computed the Raleigh_Base scenario concentrations for reference:
![screen shot 2015-01-28 at 9 40 41 am](https://cloud.githubusercontent.com/assets/10077162/5939466/f046180c-a6d1-11e4-8a3f-2b6813facc22.png)

I also computed the Raleigh_decUS1 scenario concentrations for reference:
![screen shot 2015-01-28 at 9 43 54 am](https://cloud.githubusercontent.com/assets/10077162/5939504/3f815fbc-a6d2-11e4-8e87-9b192740d5bd.png)

To make a rough calculation of % difference I used the a relative difference of -15ppb from the difference plot, then multiply by 100 and divide by 10ppb (base case is in the 10^1 ppb range here). So from this rough calculation I get a % difference of -150%. I looked back at the 2 plots of the hourly concentrations (above) and the shading in the base case is orange (10^1 ppb) and in the decUS1 case is green (10^-1 ppb).. this would be about a -200% difference. Since we decided to limit the % difference scale from -100% to 100% I would expect there to be a gradient from the -100% color to the 0% color to the southeast of the road segment that I modified.

**Comment by michellegrace** [comment]
I re-ran with the previous scenario and this looks MUCH better. 

For the relative difference I get:
![screen shot 2015-01-28 at 12 40 39 pm](https://cloud.githubusercontent.com/assets/10077162/5943222/1835abfc-a6eb-11e4-8cfb-f3849e5af960.png)

For the % difference I get:
![screen shot 2015-01-28 at 12 42 03 pm](https://cloud.githubusercontent.com/assets/10077162/5943230/22088c30-a6eb-11e4-89a0-73185274bde1.png)

Now these look correct to me. I have a suggestion on the color scale, I will add that to issue #61.
