### ISSUE TITLE
Small issue with the multipliers in modify roads window

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#63]
I hit apply on this window:
![screen shot 2015-01-29 at 1 06 15 pm](https://cloud.githubusercontent.com/assets/10077162/5963156/c282f2aa-a7b7-11e4-8d76-6ae82c3c65ea.png)

The speed changes were applied correctly. Also when the multiplier was >0 for the gas/diesel car/truck multipliers this was applied correctly. 

The problem is when the multiplier is zero, as the Diesel Car and the AADT multipliers are here. The multiplier of zero should be applied... this would create an AADT of zero on these links and a Diesel car "percentage" of zero. 

Note: the AADT of zero would essentially "erase" these roadways from the modeling, however they can be left in the source file, one of the first loops in the computation is a logical to check if the AADT == 0, so the contribution from this roadway is zero and the program moves on without wasting time on this roadway.

Tested on treehug ~1pm 1/29/15.

**Comment by nathan-rice** [comment]
Fixed
