### ISSUE TITLE
Time out warning for the user

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#64]
I never got a time out warning when I submitted this job:
![screen shot 2015-01-29 at 1 50 54 pm](https://cloud.githubusercontent.com/assets/10077162/5963896/0cf1ad9e-a7be-11e4-9c3c-a034a7afc0fc.png)

From the stop watch you can see it has gone beyond the 1000 seconds that was perviously mentioned as the server time limit in issue #40. There should be a time out warning given to the user that states something like "Server time out. Consider reducing your modeling domain to decrease computational time." 

Note: this timeout was created probably because I did not select a pollutant in the drop down menu. This is why a "default" for all drop down menus should be given. For the risk calculations, the "default" is a blank entry on the drop down menu. This is related to issue #17. I will add this to my comments on #17... both of these issues should be fixed.

Tested on treehug ~1:30pm 1/29/15.

**Comment by nathan-rice** [comment]
Fixed.

**Comment by michellegrace** [comment]
Nathan, I reopened this so you can fix the spelling and grammar of this error message. I received the error as below... 
![screen shot 2015-02-02 at 2 30 54 pm](https://cloud.githubusercontent.com/assets/10077162/6007607/845be1d2-aae9-11e4-9a2b-4a4efaa25c5f.png)

Please change “sever” to “server”. Also it is a run-on sentence, please change the “,” to “;” and put “.” at the end.

**Comment by nathan-rice** [comment]
Sure.
