### ISSUE TITLE
Know Issues link on information window

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#65]
Please add a link, "Known issues", above the "Give feedback" link on the information window. 

This should link to the C-LINE CMAS page where the user was given the username and password to access C-LINE (https://www.cmascenter.org/r-line/c-line.cfm?).

Thanks.

**Comment by nathan-rice** [comment]
Done

**Comment by michellegrace** [comment]
Nathan,
This is showing up next to the “Give feedback” link, this could be a little confusing, can you make them one above the other?

Thanks.
Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by nathan-rice** [comment]
One on top of the other looked bad.  There is a large gap between them now.

**Comment by michellegrace** [comment]
Yep. That looks better, Thanks.
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>
