### ISSUE TITLE
Annual Average problem in fortran code: please update fortran program

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#67]
Nathan,
We found a strange problem in the annual average program only for the Raleigh,NC & Charlotte,NC areas. I traced this back to a bad index in one of my fortran codes, which I fixed. Please update the C-LINE programs to the executable in this directory: /nas01/depts/ie/cempd/EPA-RARE/MGScode/CLINE_DispEmis_2-5-15

We plan to test this once you make the update, if we are convinced that this solved the problem we can move ahead with the release. Sarav will give you the final "OK" to push treehug to ctools after our testing.

Thanks. Michelle

**Comment by nathan-rice** [comment]
Forgot to close this.  Fixed.
