### ISSUE TITLE
add redirects for URLs

### ISSUE THREAD

**Issue by cseppan** [nathan-rice/ctools#68]
Both

http://ctools.its.unc.edu/
http://ctools.its.unc.edu/ctools/

can do an external redirect to http://ctools.its.unc.edu/ctools/cline/. Seems like 301 Permanent should be fine.

**Comment by cseppan** [comment]
Also redirect ctools/cport/ to ctools/cline/.

**Comment by nathan-rice** [comment]
Better if it is a temporary redirect.  Done.
