### ISSUE TITLE
Bad concentrations for Knoxville summer convective weekend off-peak NOx

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#69]
The map shows no concentrations:
![knoxville_summerconvective_badconcs_02062015](https://cloud.githubusercontent.com/assets/10145737/6083572/a0843ec0-adf7-11e4-84fc-cd6d2752a33e.PNG)
And the concentrations.csv file shows all concentrations having value -1.59E+11:
![knoxville_summerconvectivecsv_badconcs_02062015](https://cloud.githubusercontent.com/assets/10145737/6083584/bc7b2314-adf7-11e4-9594-e415b92e4b71.PNG)

**Comment by michellegrace** [comment]
Did you download the files for this run? I would like to run it offline.

Thanks.
-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490  Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by joellenb** [comment]
Here you are.

Jo Ellen

**Comment by michellegrace** [comment]
Nathan,
For some reason these records are missing from the 5cond met file, I think this file got corrupted at some point and no longer contains all the met stations.... I would like to stop making multiple copies of this and make a soft link strait to the source... please update your directories to point to 
/nas01/depts/ie/cempd/EPA-RARE/meteorology/met_conditions/met_5cond_national_NWS_sites_by_L_quantilesMGS.csv

I will update this in the current "2-5-15" directory, if you want to take it straight from there. 

... I am still tracking down how this happened, but it appears that the current file is only 433KB, the original is 535MB.

This should solve the problem for Knoxville, and potentially others that we have not stubbled upon yet.

-Michelle

**Comment by arunacs** [comment]
Michelle,
Can you add group rx permissions to the 2-5-15 dir?

killdevil-login1:/nas01/depts/ie/cempd/EPA-RARE/MGScode%  l
total 140
drwx------  5 mgs3584 cep-emc 4096 Feb  6 13:00 CLINE_DispEmis_2-5-15

**Comment by nathan-rice** [comment]
Updated
