### ISSUE TITLE
Smaller initial geographic extents? Annual average server time out errors.

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#72]
I tried running an annual average with Raleigh, NC as it comes up when you put it in the search box. This will not run an annual average. I tried zooming in and everything works fine, so I think the calculation for the whole area is just timing out on the server. Maybe there are too many roads?

To verify... I tried this for the Atlanta, GA and NYC, NY area, which have dense road networks. The annual average in these areas also times out. When I try this for a place like Gainesville, FL, which has a less dense road network it runs just fine.

Its not a show stopper for me, I can add this to the list of known issues, by saying something like:  "If the server times out, you should try a smaller geographic domain". 

One way to prevent this in some cases is to make the initial area that is loaded when a location is typed in the search field smaller. If this domain was smaller initially users are less likely to zoom out where we have server time out issues.

Tested on tree hug 2/6/15 ~1:30pm.

**Comment by nathan-rice** [comment]
I don't think  making the initial window extent smaller everywhere for overly dense corner cases is a good way to deal with this problem.

A better solution would be to limit the number of road segments returned from the database on a spatial intersection query, so the corner cases disappear.

**Comment by michellegrace** [comment]
Agreed, loading less roadways is a great option, however we have not built this architecture into the databases or the back-end of the tool. This will take time, and we would like to get a release where users are able to model major cities, not something that will hang because of runtimes.

I did download some hourly files and run the annual average C-LINE code offline, this is taking the same amount of time as before, on average 250 seconds for a large roadway dense city. How come the single scenario annual averages are now timing out? This means comparisons for these larger cities are out of the question.

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by nathan-rice** [comment]
We haven't built this architecture into the database or back end of the tool?  How do you know?

The truth is, loading fewer roadways is as simple as appending a .limit(xxx) to the postgis intersection query - not even one line of code.  If the roadways had an integer field associated with them that went from smallest -> largest (or vice versa) I could also add a .sort_by(road_size_field) to get high impact roads, and we're still not even at a full line of code changed.

**Comment by michellegrace** [comment]
Correct, we discussed assigning an integer to the roadways to assist in this loading.. However this has not been determined or added to the database, thus it is not present in the current database.

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by nathan-rice** [comment]
Yet I still have the ability to put a limit on the number of roadways returned, which is the right way to deal with the dense road networks problem.

Didn't you say that NFC class was already present in the road database?  Is this value linearly increasing in relation to road size, or are there cases like for instance a 08 being greater than a 11?

**Comment by michellegrace** [comment]
You can use the second digit of the NFC class. This then all 1’s are the “biggest” roadways, increasing number means the roadway is getting “smaller".

How are you going to handle when all roadways can be loaded and run? Like for instance now you can go to a relatively small city like Gainsville, FL and annual averages run fine with all roadways. But you have the same size geographic extent for a more dense city like Raleigh, NC and annual averages time out. Are you letting the user determine which types of roads are loaded? You wont necessarily know how long the annual run will take unless you do it, so how do you know how many roads to load?

I also think this is an interpolation issue, I think the hourly and annual average runtimes for the web tool have significantly increased in the last month or so, while the dispersion code has remained similar in runtime. I know I have run annual averages for Raleigh in the past and they have completed and not timed out, now all runs with Raleigh time out.

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by nathan-rice** [comment]
When you apply a limit to a query, if the number of results is below that limit, all results are returned.  Thus, all we need to do is determine the maximum number of road segments we can complete with a reasonable run time and use that as the query limit.

As for what type of roads are returned, I will just use the NFC class.

**Comment by nathan-rice** [comment]
When you apply a limit to a query, if the number of results is below that limit, all results are returned.  Thus, all we need to do is determine the maximum number of road segments we can complete with a reasonable run time and use that as the query limit.

As for what type of roads are returned, I will just use the NFC class.

**Comment by michellegrace** [comment]
This is not as simple as using the NFC and then limited the number of roadways to 1000 (or whatever the max is). You do not want to take the top 1000 roads strictly... Suppose you have 750 interstate links and 750 highway links, then selecting the first 1000 leads to having only 250 of the highway links.. this is not intelligent, you need to have all or non of each type of roadway. I think this feature will take some work.....

**Comment by joellenb** [comment]
I agree that there are quite a few design decisions that will need to be made by the group before this issue can be "solved". I believe that (a) if the computation times out, and (b) if the error message is displayed for the user, then C-LINE already says to select a smaller geographic region. We also need to check that this issue is documented in places that are easy for the user to find - known issues page, help for the type of analysis, others? 
For a "simple Band-aid" I like the idea of automatically zooming the map region tighter on the city that the user selects. Depending upon the area that may sufficiently reduce the number of road links to avoid the timeout issue.
I anticipate that a more complete solution will require changes to the user interface, programming, and/or database. But before we can propose solutions we need to identify the limiting factor/factors. Is it geographic extent, road segments, sources, receptors, data transfer, dispersion calculations, interpolation for results, or other aspects?

We may want to split this issue into 2: 1 for immediate fix and 1 for design work for a future release.

**Comment by michellegrace** [comment]
Also remember that runtime is tied to how many receptors are in the domain. Since we are still doing an interpolation of the receptor grid, we may be able to scale back some here without affecting the end result.

**Comment by nathan-rice** [comment]
I've implemented a hard limit of 1000 road segments loaded at a time, sorted by fclass_rev; this limit thins out raleigh slightly, and new york massively.  This will solve the timeout problem in all circumstances.  If you can still make it timeout, let me know and I'll adjust the roads count.

I've also increased the initial zoom to encourage users to model smaller domains.

As for thinning out receptors, the portion of receptors generated by the regular grid is fairly small - the bulk of them come from flanking the road network.

**Comment by michellegrace** [comment]
This hard limit creates problems where you have a very choppy looking road network. Here is NYC:
![screen shot 2015-02-16 at 8 23 03 am](https://cloud.githubusercontent.com/assets/10077162/6212703/2a3fd42e-b5b6-11e4-8392-0e803acf544b.png)

Notice the choppiness of the road network in Brooklyn, you have some road links in neighborhoods like Flatlands represented and others are not present. This is also the case for Manhattan, there are some roadways in the mid and southern tip, but roadways of the same class are missing in the middle and upper part of manhattan.

Also, the above image is the initial geographic extent that you get by typing "New York City" in the search box. I was not able to run the annual average, it timed out. When I ran the hourly computation I got an image that looks like this:
![screen shot 2015-02-16 at 8 41 46 am](https://cloud.githubusercontent.com/assets/10077162/6212855/ac240ffe-b5b7-11e4-82a7-e5109b7d6325.png)

From my comment earlier on this issue: You do not want to take the top 1000 roads strictly... Suppose you have 750 interstate links and 750 highway links, then selecting the first 1000 leads to having only 250 of the highway links.. this is not intelligent, you need to have all or none of each type of roadway.

The other compounding factor for the runtimes is the number of receptors. I downloaded these runs and the number of receptors is very high (>14,000). The number of road links is one thing, if you double the road links you double the runtime, but this also holds true for receptors, if you you double the number of receptors you double the runtime. Im not sure how these receptors are created, but this needs to be examined to decrease runtime.

**Comment by nathan-rice** [comment]
Receptors are created according to the scheme that you came up with.

Modeling as many road segments as possible seems perfectly intelligent to me.  I would rather have a choppy road network that is a better approximation of reality.  It is probably a good idea to inform the user that only 1000 road segments can be modeled simultaneously for computational reasons, so they don't wonder why new roads appear when they zoom in.

**Comment by joellenb** [comment]
The default zoom level when I select St. Louis is too large on treehug. When I selected annual average concentration I eventually get the message :"A server error occurred; please check your inputs before submitting again.".

**Comment by michellegrace** [comment]
It makes common sense for the user to see only major roads, then as they zoom in to see smaller streets... this is how google maps works, this is how our adaptive loading should work.

**Comment by nathan-rice** [comment]
I disagree.

**Comment by arunacs** [comment]
Nathan,

This threshold of top 1000 road-links raises more questions than answers. Please remove that for now, and we will revisit this for the May release with additional testing. I like the new increased level of default zoom. It seems to address the timeout issue in most cases, at least for now. We will just educate the user to use smaller domains till we come up with a refined solution.
