### ISSUE TITLE
Treehug is down with an nginx error

### ISSUE THREAD

**Issue by michellegrace** [nathan-rice/ctools#90]
I get the following error when I got to the treehug site:
![screen shot 2015-02-11 at 9 59 37 am](https://cloud.githubusercontent.com/assets/10077162/6149168/cc14be94-b1d4-11e4-863b-9a0e9edffbcc.png)

I noticed this when I got into the office this morning (2/11/15 7:30am). It was working yesterday afternoon when I left the office (2/10/15 4pm).

**Comment by joellenb** [comment]
Error still occurs on Thursday 2/12 at 9:33 AM
