### ISSUE TITLE
Legend needs to be cleared when user goes to a new location

### ISSUE THREAD

**Issue by joellenb** [nathan-rice/ctools#94]
When C-LINE completes a simulation successfully it draws the interpolated results and a legend. The results are tied to the underlying map but the legend is not.

![raleigh_hrly_default_02172015](https://cloud.githubusercontent.com/assets/10145737/6231642/f5c54c8a-b694-11e4-90ad-909d567aad5a.PNG)

If the user then selects a different geographic area for the next analysis, the legend remains on the screen. 

![charlotte_oldlegend_02172015](https://cloud.githubusercontent.com/assets/10145737/6231655/0fafe056-b695-11e4-9daf-b81852a9c9e7.PNG)

The legend, as well as the map of results, needs to be cleared when the user selects a different location.

**Comment by nathan-rice** [comment]
Done
